repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: "v1.5.5"
    hooks:
      - id: forbid-crlf
      - id: remove-crlf

  - repo: https://github.com/executablebooks/mdformat
    rev: "0.7.22"
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.13.0"
    hooks:
      - id: ruff-check
      - id: ruff-format
