repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: "v1.5.5"
    hooks:
      - id: forbid-crlf
      - id: remove-crlf

  - repo: https://github.com/executablebooks/mdformat
    rev: "0.7.22"
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.17.1"
    hooks:
      - id: mypy
        args:
          - --strict
          - --ignore-missing-imports
          - --no-warn-unused-ignores
        additional_dependencies:
          - types-setuptools
          - types-toml
          - types-click

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.11"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
