[package]
name = "rayt_python"
version = "0.1.0"
edition = "2021"

[lib]
name = "rayt_python"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22.4", features = ["extension-module", "abi3-py39"] }
rand = "0.8.5"
