[project]
name = "rayt"
version = "0.1.0"
description = "Ray Tracing with Python"
authors = [
  { name = "Gökmen Görgen", email = "gkmngrgn@gmail.com" },
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "numba>=0.57.0",
    "numpy>=2.2.6",
]

[project.optional-dependencies]
cuda = [
    "cupy>=13.0.0",
]

[project.scripts]
one-weekend = "rayt.cli:one_weekend"

[tool.uv]
package = true
