[project]
name = "rayt"
version = "0.1.0"
description = "Ray Tracing with Python & Rust"
authors = [
  { name = "Gökmen Görgen", email = "gkmngrgn@gmail.com" },
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
]

[project.scripts]
one-weekend = "rayt.cli:one_weekend"

[tool.maturin]
module-name = "rayt_python"
python-packages = ["rayt"]
python-source = "src"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
