class Vec3:
    def __init__(self, x: float, y: float, z: float) -> None: ...
    @staticmethod
    def random(min_max: float | None) -> Vec3: ...

class Ray:
    def __init__(self, origin: Vec3, direction: Vec3) -> None: ...
    @property
    def direction(self) -> Vec3: ...

class Lambertian:
    def __init__(self, albedo: Vec3) -> None: ...

def random_double(min: float = 0.0, max: float = 1.0) -> float: ...
def unit_vector(v: Vec3) -> Vec3: ...
def write_color(pixel_color: Vec3, samples_per_pixel: int) -> None: ...
