class Vec3:
    def __init__(self, x: float, y: float, z: float) -> None: ...
    def __add__(self, other: Vec3) -> Vec3: ...

class Color(Vec3): ...
class Point3(Vec3): ...

class Camera:
    def __init__(
        self,
        lookfrom: Point3,
        lookat: Point3,
        vup: Vec3,
        vfov: float,
        aspect_ratio: float,
        aperture: float,
        focus_dist: float,
    ) -> None: ...
    def get_ray(self, s: float, t: float) -> Ray: ...

class HittableList:
    def __init__(self) -> None: ...

class Ray:
    def __init__(self, origin: Point3, direction: Vec3) -> None: ...

def random_double(min: float = 0.0, max: float = 1.0) -> float: ...
def unit_vector(v: Vec3) -> Vec3: ...
def write_color(pixel_color: Vec3, samples_per_pixel: int) -> None: ...
