[tool.poetry]
name = "rayt-python"
version = "0.1.0"
description = "Ray tracing with Python"
authors = ["Gökmen Görgen <gkmngrgn@gmail.com>"]
license = "MIT"
packages = [{include = "rayt_python"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
